services:
  apisix-admin-panel:
    image: apisix-dashboard-cloud:latest
    container_name: apisix-dashboard-ssl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
    # 如需加入现有后端网络，可取消注释并设置为你的网络名称
    # networks:
    #   - apisix-network

# networks:
#   apisix-network:
#     external: true
#     name: 01_apisix_backend_default



openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
  -subj "/CN=113.44.57.186" \
  -addext "subjectAltName=IP:113.44.57.186" \
  -keyout ./certs/privkey.pem -out ./certs/fullchain.pem